#define MAXLEVEL 21
#define REWARDGOLE_PER_MINUTES 5
#define BACTERIAL_BASIC_SCORE 5
#define ENEMY_BASIC_EXP 10
#define ENEMY_EVOLUTION_BASIC_TIME 20.f
#define ENEMY_EVOLUTION_MAX_TIME 60.f
#define BECTERIAL_MESSAGE @"Becterial.BecterialTouched"

#if (CC_TARGET_PLATFORM == CC_PLATFORM_WIN32)
#define BLOCK_SIZE 121.f
#else
#define BLOCK_SIZE 60.5f
#endif